/**
 * One-off content migration: append a batch of commonly-searched pediatric
 * conditions to data/database.source.json. Idempotent — skips ids already
 * present. After running, `node build_db.js` validates and regenerates.
 *
 * Clinical content is intentionally conservative: generic active ingredients
 * only (no brands, no doses), explicit "see a doctor" thresholds, and urgency
 * levels that err toward caution.
 */
const fs = require('fs');
const path = require('path');

const srcPath = path.join(__dirname, '..', 'data', 'database.source.json');
const db = JSON.parse(fs.readFileSync(srcPath, 'utf8'));

const img = name => `assets/illustrations/${name}.svg`;

const NEW = [
    {
        id: 'common_cold', body_system: 'resp', category: 'resp_upper',
        name: 'Common Cold (Viral Nasopharyngitis)',
        classification: 'Self-limiting viral upper respiratory tract infection.',
        affected_age_group: 'All ages; infants and preschoolers average 6–10 colds per year.',
        causes: 'More than 200 viruses, most commonly rhinoviruses, also coronaviruses, RSV, and parainfluenza, spread by respiratory droplets and contaminated hands and surfaces.',
        pathophysiology: 'The virus infects the lining of the nose and throat, triggering local inflammation, increased mucus production, and swelling that produce the familiar congestion and runny nose.',
        symptoms_early: 'Sneezing, sore or scratchy throat, clear runny nose, and mild tiredness.',
        symptoms_progressive: 'Nasal congestion with thicker yellow or green mucus, cough, low-grade fever, and reduced appetite over several days.',
        symptoms_severe: 'High or persistent fever, fast or labored breathing, ear pain, wheezing, or signs of dehydration suggest a complication rather than a simple cold.',
        urgency_level: 'mild',
        diagnosis_methods: 'Clinical diagnosis based on typical symptoms and examination; testing is rarely needed unless influenza, COVID-19, or a bacterial complication is suspected.',
        treatment_plan: 'Supportive care only. Antibiotics do not help viral colds. Focus on rest, fluids, and comfort while the infection clears on its own.',
        home_care: 'Offer plenty of fluids and rest. Use saline nose drops with gentle bulb suction for blocked infant noses, run a cool-mist humidifier, and keep the child comfortable. Honey may ease cough in children over 1 year.',
        medicinal_elements: 'Saline nasal drops (drug-free decongestion for infants); Acetaminophen/Paracetamol (active ingredient for fever and discomfort); Ibuprofen (anti-inflammatory active ingredient for children over 6 months).',
        when_to_see_doctor: 'See a doctor for any fever in a baby under 3 months, breathing difficulty, dehydration, ear pain, symptoms lasting beyond 10 days, or a fever that returns after starting to improve. Avoid over-the-counter cough-and-cold combination medicines in children under 6.',
        prevention: 'Frequent handwashing, teaching children to cough into their elbow, not sharing cups or utensils, and keeping hands away from the face reduce spread.',
        vaccination_info: 'No vaccine prevents the common cold, but annual influenza vaccination prevents the more serious flu that is often confused with a cold.',
        prognosis: 'Excellent. Colds resolve on their own without lasting effects.',
        recovery_timeline: 'Symptoms peak around days 2–3 and usually settle within 7–10 days; a lingering cough can persist a little longer.',
        complications: 'Ear infections (otitis media), sinusitis, asthma flare-ups, and occasionally pneumonia, especially in young infants.',
        related_diseases: ['Pediatric Influenza (Flu)', 'Acute Tonsillopharyngitis', 'Acute Otitis Media (AOM)', 'Acute Sinusitis (Pediatric)', 'Acute Viral Bronchiolitis'],
        tags: ['cold', 'runny nose', 'cough', 'viral', 'congestion'],
        imagePath: img('microbe')
    },
    {
        id: 'influenza', body_system: 'resp', category: 'resp_upper',
        name: 'Pediatric Influenza (Flu)',
        classification: 'Acute systemic viral respiratory infection caused by influenza viruses.',
        affected_age_group: 'All children; highest complication risk under 5 years, especially under 2 years.',
        causes: 'Influenza A and B viruses spread by respiratory droplets and contaminated surfaces, circulating mainly in seasonal winter epidemics.',
        pathophysiology: 'Influenza infects the respiratory lining and provokes a vigorous immune response, producing the abrupt high fever, body aches, and exhaustion that distinguish flu from an ordinary cold.',
        symptoms_early: 'Sudden high fever, chills, headache, sore throat, and prominent muscle aches that come on quickly.',
        symptoms_progressive: 'Dry cough, nasal congestion, marked fatigue, and sometimes vomiting or diarrhea in younger children.',
        symptoms_severe: 'Fast or difficult breathing, bluish lips, chest pain, persistent dizziness, seizures, severe weakness, or dehydration require urgent care.',
        urgency_level: 'moderate',
        diagnosis_methods: 'Usually clinical during flu season; rapid antigen or PCR swabs confirm the diagnosis when it would change management, such as starting antiviral medication.',
        treatment_plan: 'Most children recover with rest and fluids. Antiviral active ingredients may be prescribed by a clinician for high-risk children or severe illness, ideally within 48 hours of onset.',
        home_care: 'Encourage rest and frequent fluids, treat fever for comfort, and keep the child home until fever-free for 24 hours without medicine. Watch breathing and hydration closely.',
        medicinal_elements: 'Oseltamivir (antiviral active ingredient prescribed by a clinician for selected cases); Acetaminophen/Paracetamol (fever and aches); Ibuprofen (over 6 months). Never give aspirin to children with flu.',
        when_to_see_doctor: 'Seek care urgently for trouble breathing, bluish color, dehydration, seizures, a child too lethargic to wake, or any fever in a baby under 3 months. High-risk children (asthma, heart disease, under 2 years) should be assessed early.',
        prevention: 'Annual influenza vaccination is the best protection. Handwashing and staying away from sick contacts help reduce spread.',
        vaccination_info: 'Annual flu vaccine is recommended for all children from 6 months of age, with two doses the first season for the youngest children.',
        prognosis: 'Most children recover fully within 1–2 weeks; serious complications are uncommon but more likely in the very young and those with chronic conditions.',
        recovery_timeline: 'Fever typically lasts 3–5 days; cough and fatigue can linger for up to two weeks.',
        complications: 'Pneumonia, ear infections, dehydration, worsening of asthma, and rarely febrile seizures or encephalitis.',
        related_diseases: ['Common Cold (Viral Nasopharyngitis)', 'Pediatric Pneumonia', 'Acute Viral Bronchiolitis', 'Febrile Seizures'],
        tags: ['flu', 'influenza', 'fever', 'viral', 'respiratory'],
        imagePath: img('microbe')
    },
    {
        id: 'pneumonia', body_system: 'resp', category: 'resp_lower',
        name: 'Pediatric Pneumonia',
        classification: 'Infection and inflammation of the lung tissue (alveoli).',
        affected_age_group: 'All ages; a leading cause of serious illness in children under 5 worldwide.',
        causes: 'Viruses (including RSV and influenza) are the most common cause in young children; bacteria such as Streptococcus pneumoniae and Mycoplasma cause many cases in older children.',
        pathophysiology: 'Infection inflames the small air sacs of the lungs, which fill with fluid and pus, reducing the surface available for oxygen exchange and causing cough and breathlessness.',
        symptoms_early: 'Fever, cough, and faster breathing, often following a cold or sore throat.',
        symptoms_progressive: 'Labored breathing with chest in-drawing, reduced feeding or appetite, tiredness, and sometimes chest or abdominal pain.',
        symptoms_severe: 'Bluish lips, grunting, severe in-drawing of the chest, inability to drink, drowsiness, or oxygen levels needing hospital support.',
        urgency_level: 'severe',
        diagnosis_methods: 'Clinical assessment of breathing rate and effort, listening to the chest, oxygen saturation measurement, and a chest X-ray or blood tests when needed.',
        treatment_plan: 'Bacterial pneumonia is treated with clinician-prescribed antibiotics; viral pneumonia is managed supportively. Oxygen and hospital care are used for severe cases.',
        home_care: 'For mild cases managed at home, give prescribed medicine exactly as directed, ensure rest and fluids, and monitor breathing rate and color closely. Do not stop antibiotics early.',
        medicinal_elements: 'Amoxicillin (first-line antibacterial active ingredient prescribed for typical bacterial pneumonia); Acetaminophen/Paracetamol or Ibuprofen (fever and comfort); supplemental oxygen (hospital supportive therapy).',
        when_to_see_doctor: 'Seek care promptly for fast or hard breathing, chest in-drawing, bluish lips, poor feeding, or persistent high fever. Any breathing difficulty in an infant is an emergency.',
        prevention: 'Pneumococcal (PCV) and Hib vaccines, annual flu vaccine, exclusive breastfeeding in infancy, handwashing, and avoiding tobacco smoke all reduce risk.',
        vaccination_info: 'PCV, Hib, measles, pertussis, and influenza vaccines all prevent major causes of childhood pneumonia and are core to the routine schedule.',
        prognosis: 'Most children recover fully with timely treatment; outcomes are worse when care is delayed or in malnourished children.',
        recovery_timeline: 'Fever often improves within 48–72 hours of effective treatment; cough and tiredness can persist for 1–3 weeks.',
        complications: 'Pleural effusion or empyema (fluid around the lung), low blood oxygen, dehydration, and spread of infection to the bloodstream.',
        related_diseases: ['Acute Viral Bronchiolitis', 'Pediatric Influenza (Flu)', 'Pediatric Asthma', 'Acute Bronchitis'],
        tags: ['pneumonia', 'lung infection', 'breathing difficulty', 'fever', 'cough'],
        imagePath: img('microbe')
    },
    {
        id: 'sinusitis', body_system: 'ent', category: 'ent_pharyngeal',
        name: 'Acute Sinusitis (Pediatric)',
        classification: 'Inflammation or infection of the paranasal sinuses, usually following a cold.',
        affected_age_group: 'Children of all ages, more recognizable after about age 1 once sinuses develop.',
        causes: 'Most often a viral cold that blocks sinus drainage; a minority develop secondary bacterial infection. Allergies can predispose.',
        pathophysiology: 'Swelling of the nasal lining blocks the sinus openings, trapping mucus that becomes a medium for inflammation or bacterial overgrowth.',
        symptoms_early: 'Nasal congestion and discharge with a daytime cough that persists beyond the usual cold.',
        symptoms_progressive: 'Cold symptoms lasting more than 10 days without improvement, or thick colored nasal discharge with fever, facial pressure, or bad breath.',
        symptoms_severe: 'Swelling or redness around the eye, severe headache, vision changes, high fever, or neck stiffness require urgent evaluation.',
        urgency_level: 'mild',
        diagnosis_methods: 'Clinical diagnosis from symptom pattern and duration; imaging is reserved for suspected complications, not routine cases.',
        treatment_plan: 'Many cases resolve on their own. Antibiotics are prescribed by a clinician for persistent, worsening, or severe bacterial sinusitis.',
        home_care: 'Saline nasal rinses or drops, adequate fluids, a humidifier, and rest. Treat discomfort and fever as needed.',
        medicinal_elements: 'Saline nasal irrigation (drug-free drainage support); Amoxicillin or amoxicillin-clavulanate (antibacterial active ingredients when bacterial infection is diagnosed); Acetaminophen/Paracetamol or Ibuprofen (pain and fever).',
        when_to_see_doctor: 'See a doctor for cold symptoms lasting beyond 10 days, high fever with thick discharge, facial swelling, eye swelling or redness, or severe headache.',
        prevention: 'Treating allergies, handwashing, avoiding tobacco smoke, and keeping up with routine vaccines reduce episodes.',
        vaccination_info: 'Pneumococcal and Hib vaccines reduce some bacterial causes of sinus infection.',
        prognosis: 'Excellent; most children recover completely.',
        recovery_timeline: 'Viral sinusitis improves within about 10 days; bacterial cases improve within a few days of starting appropriate antibiotics.',
        complications: 'Spread to the tissues around the eye (orbital cellulitis) or, rarely, to the brain — both are emergencies.',
        related_diseases: ['Common Cold (Viral Nasopharyngitis)', 'Allergic Rhinitis (Hay Fever)', 'Acute Otitis Media (AOM)'],
        tags: ['sinusitis', 'sinus infection', 'congestion', 'facial pressure'],
        imagePath: img('throat')
    },
    {
        id: 'constipation', body_system: 'gastro', category: 'gastro_chronic',
        name: 'Functional Constipation',
        classification: 'Common functional disorder of infrequent or painful, hard bowel movements without an underlying disease.',
        affected_age_group: 'All ages; peaks at toilet training, starting solids, and school entry.',
        causes: 'Usually behavioral and dietary — stool withholding after a painful movement, low fiber or fluid intake, and toileting changes; rarely an underlying medical cause.',
        pathophysiology: 'Withholding lets stool stay in the colon longer, where more water is absorbed, making it harder and more painful to pass — a cycle that reinforces withholding.',
        symptoms_early: 'Fewer than three bowel movements a week, hard or pellet-like stools, and straining.',
        symptoms_progressive: 'Painful movements, stool withholding postures, abdominal pain, reduced appetite, and sometimes soiling (leakage) of liquid stool around hard stool.',
        symptoms_severe: 'Marked abdominal swelling, vomiting (especially green), blood in stool, or weight loss point to a more serious problem needing assessment.',
        urgency_level: 'mild',
        diagnosis_methods: 'Clinical diagnosis from history and examination; tests are rarely needed unless warning signs suggest an underlying condition.',
        treatment_plan: 'Disimpaction if needed, then maintenance with a clinician-guided osmotic laxative plus dietary and toileting changes, continued long enough to break the withholding cycle.',
        home_care: 'Increase fiber (fruits, vegetables, whole grains) and fluids, encourage regular unhurried toilet sitting after meals, and use praise rather than pressure. Keep a simple stool diary.',
        medicinal_elements: 'Polyethylene glycol (osmotic laxative active ingredient commonly used under clinician guidance); lactulose (alternative osmotic agent); dietary fiber (drug-free stool softening).',
        when_to_see_doctor: 'See a doctor for constipation in a baby under a few weeks old, failure to pass meconium in the first 48 hours of life, blood in stool, vomiting, poor weight gain, severe pain, or constipation not responding to simple measures.',
        prevention: 'A fiber-rich diet, good hydration, regular activity, and a calm, consistent toileting routine prevent most cases.',
        vaccination_info: 'No vaccine is relevant to functional constipation.',
        prognosis: 'Very good with consistent treatment, though relapses are common and maintenance therapy may be needed for months.',
        recovery_timeline: 'Improvement often within days of disimpaction; maintenance therapy typically continues for several months to prevent recurrence.',
        complications: 'Painful anal fissures, stool soiling, recurrent withholding, and reduced appetite.',
        related_diseases: ['Hirschsprung Disease (Congenital Megacolon)', 'Celiac Disease (Gluten-Sensitive Enteropathy)', 'Congenital Hypothyroidism'],
        tags: ['constipation', 'hard stool', 'withholding', 'toileting'],
        imagePath: img('stomach_ache')
    },
    {
        id: 'gastroenteritis', body_system: 'gastro', category: 'gastro_acute',
        name: 'Acute Gastroenteritis (Stomach Flu)',
        classification: 'Acute infection of the stomach and intestines causing diarrhea and vomiting.',
        affected_age_group: 'All ages; dehydration risk is highest in infants and toddlers.',
        causes: 'Most often viruses (rotavirus, norovirus); also bacteria and parasites from contaminated food or water and person-to-person spread.',
        pathophysiology: 'Infection of the gut lining disrupts fluid absorption and increases secretion, producing watery diarrhea and vomiting that can quickly deplete body fluids in small children.',
        symptoms_early: 'Nausea, vomiting, and the onset of loose or watery stools, sometimes with low-grade fever.',
        symptoms_progressive: 'Frequent watery diarrhea, crampy abdominal pain, reduced appetite, and early signs of dehydration such as decreased urination.',
        symptoms_severe: 'Signs of significant dehydration (no wet diaper for 8+ hours, no tears, sunken eyes, lethargy), blood in stool, persistent green vomiting, or high fever.',
        urgency_level: 'moderate',
        diagnosis_methods: 'Clinical diagnosis; stool testing is reserved for blood in stool, prolonged illness, recent travel, or suspected bacterial or parasitic causes.',
        treatment_plan: 'The priority is rehydration with oral rehydration solution. Most children do not need medication; antibiotics are only for specific confirmed bacterial infections.',
        home_care: 'Give frequent small amounts of oral rehydration solution, continue breastfeeding, and resume a normal diet as tolerated once vomiting settles. Avoid sugary drinks, which can worsen diarrhea.',
        medicinal_elements: 'Oral rehydration solution (ORS) (electrolyte and glucose active formulation, the mainstay of treatment); zinc (active supplement that shortens diarrhea in young children); rotavirus vaccine (preventive).',
        when_to_see_doctor: 'Seek care for signs of dehydration, blood in stool, persistent vomiting preventing fluids, high fever, severe abdominal pain, or illness in a young infant.',
        prevention: 'Handwashing, safe food and water, and rotavirus vaccination prevent many cases.',
        vaccination_info: 'The oral rotavirus vaccine series in infancy prevents the most severe viral gastroenteritis.',
        prognosis: 'Excellent with adequate rehydration; most viral cases resolve without complications.',
        recovery_timeline: 'Vomiting usually settles within 1–2 days; diarrhea typically lasts 3–7 days.',
        complications: 'Dehydration and electrolyte imbalance, and in some bacterial infections, hemolytic uremic syndrome.',
        related_diseases: ['Pediatric Dehydration', 'Rotavirus Gastroenteritis', 'Shigellosis', 'Hemolytic Uremic Syndrome (HUS)'],
        tags: ['gastroenteritis', 'stomach flu', 'diarrhea', 'vomiting', 'dehydration'],
        imagePath: img('stomach_ache')
    },
    {
        id: 'gerd_infant', body_system: 'gastro', category: 'gastro_chronic',
        name: 'Gastroesophageal Reflux (Infant GER/GERD)',
        classification: 'Backflow of stomach contents into the esophagus; common and usually benign in infants.',
        affected_age_group: 'Infants, peaking around 4 months; most outgrow it by 12–18 months.',
        causes: 'An immature lower esophageal sphincter and a mostly liquid diet allow stomach contents to flow back up; reflux becomes disease (GERD) when it causes complications.',
        pathophysiology: 'The valve between the stomach and esophagus relaxes easily in infancy, allowing milk to return; most "spitting up" is normal and resolves as the sphincter matures.',
        symptoms_early: 'Frequent effortless spitting up or posseting after feeds in an otherwise happy, growing baby ("happy spitter").',
        symptoms_progressive: 'In GERD: irritability with feeds, arching, frequent vomiting, poor weight gain, refusing feeds, or persistent cough.',
        symptoms_severe: 'Forceful or projectile vomiting, green or bloody vomit, poor weight gain, breathing problems, or blood in stool need prompt evaluation.',
        urgency_level: 'mild',
        diagnosis_methods: 'Usually clinical based on history and growth. Tests (pH study, imaging, endoscopy) are reserved for severe or atypical cases or to exclude other conditions.',
        treatment_plan: 'Simple reflux needs reassurance and feeding adjustments. GERD with complications may need clinician-guided thickened feeds, a trial of a cows-milk-free diet, or acid-reducing medication.',
        home_care: 'Smaller more frequent feeds, frequent burping, holding the baby upright for 20–30 minutes after feeds, and avoiding overfeeding. Always place babies on their back to sleep.',
        medicinal_elements: 'Feed thickeners (drug-free measure under clinician guidance); a trial of an extensively-hydrolyzed formula (for suspected milk protein allergy); acid-suppressing active ingredients (only for diagnosed GERD, prescribed by a clinician).',
        when_to_see_doctor: 'See a doctor for poor weight gain, forceful or projectile vomiting, green or bloody vomit, feeding refusal, breathing problems, or reflux that distresses the baby.',
        prevention: 'Avoiding overfeeding and upright positioning after feeds reduce symptoms; most reflux is developmental and cannot be fully prevented.',
        vaccination_info: 'No vaccine is relevant to infant reflux.',
        prognosis: 'Excellent; the great majority of infants outgrow reflux by their first or second birthday.',
        recovery_timeline: 'Simple reflux steadily improves as the baby starts solids and sits upright, usually resolving by 12–18 months.',
        complications: 'In GERD: poor growth, esophageal irritation, feeding aversion, and (rarely) breathing problems.',
        related_diseases: ["Cow's Milk Protein Allergy (CMPA)", 'Infantile Hypertrophic Pyloric Stenosis'],
        tags: ['reflux', 'gerd', 'spitting up', 'infant feeding'],
        imagePath: img('stomach_ache')
    },
    {
        id: 'diaper_dermatitis', body_system: 'derm', category: 'derm_atopic',
        name: 'Diaper Dermatitis (Diaper Rash)',
        classification: 'Common irritant or fungal inflammation of the skin in the diaper area.',
        affected_age_group: 'Infants and toddlers in diapers, most common at 9–12 months.',
        causes: 'Prolonged contact with urine and stool, friction, and moisture; secondary infection with Candida yeast is common in rashes lasting more than a few days.',
        pathophysiology: 'Moisture and irritants break down the skin barrier, causing inflammation; the warm, moist environment favors yeast overgrowth that prolongs the rash.',
        symptoms_early: 'Pink to red skin over the convex areas in contact with the diaper, sparing the skin folds.',
        symptoms_progressive: 'Brighter red, tender or weepy skin; with Candida, beefy-red patches with small satellite spots that involve the folds.',
        symptoms_severe: 'Blisters, pus, open sores, spreading redness, or fever suggest bacterial infection needing medical care.',
        urgency_level: 'mild',
        diagnosis_methods: 'Clinical diagnosis from the appearance and distribution; swabs are rarely needed.',
        treatment_plan: 'Keep the area clean and dry, change diapers frequently, and apply a barrier cream. Antifungal cream is added when Candida is suspected.',
        home_care: 'Change diapers promptly, clean gently with water, allow diaper-free air time, and apply a thick zinc-oxide barrier paste at each change. Avoid scented wipes and harsh soaps.',
        medicinal_elements: 'Zinc oxide barrier paste (drug-free skin protectant); petrolatum (barrier emollient); topical antifungal active ingredients such as clotrimazole or nystatin (for Candida-associated rash).',
        when_to_see_doctor: 'See a doctor if the rash has blisters or pus, spreads beyond the diaper area, does not improve in a few days, or comes with fever.',
        prevention: 'Frequent diaper changes, gentle cleansing, air time, and routine barrier cream prevent most rashes.',
        vaccination_info: 'No vaccine is relevant to diaper rash.',
        prognosis: 'Excellent; most rashes clear within a few days of good skin care.',
        recovery_timeline: 'Irritant rashes improve within 2–3 days; yeast-related rashes clear within about a week of antifungal treatment.',
        complications: 'Secondary bacterial or yeast infection if the rash is prolonged or untreated.',
        related_diseases: ['Atopic Dermatitis (Infantile Eczema)', 'Impetigo Contagiosa'],
        tags: ['diaper rash', 'nappy rash', 'skin irritation', 'candida'],
        imagePath: img('rash')
    },
    {
        id: 'cradle_cap', body_system: 'derm', category: 'derm_atopic',
        name: 'Seborrheic Dermatitis (Cradle Cap)',
        classification: 'Common, harmless scaly scalp condition of infancy.',
        affected_age_group: 'Infants, usually appearing in the first weeks to months of life.',
        causes: 'Not fully understood; linked to maternal hormones stimulating oil glands and to a skin yeast (Malassezia). It is not caused by poor hygiene or allergy.',
        pathophysiology: 'Overactive oil glands and skin yeast produce greasy scaling on the scalp and other oil-rich areas; the process is self-limiting as the glands quiet down.',
        symptoms_early: 'Greasy yellow or white flakes and scales on the scalp.',
        symptoms_progressive: 'Thicker crusts on the scalp, sometimes spreading to the eyebrows, behind the ears, or the diaper area, usually without itch.',
        symptoms_severe: 'Widespread redness, weeping, signs of infection, or significant discomfort are unusual and warrant review.',
        urgency_level: 'mild',
        diagnosis_methods: 'Clinical diagnosis from the typical greasy scaling; no tests are needed.',
        treatment_plan: 'Most cases need no treatment and resolve on their own. Gentle measures soften and lift the scale when desired.',
        home_care: 'Massage a little baby or mineral oil into the scalp, wait a few minutes, then gently loosen scales with a soft brush and wash with a mild baby shampoo. Avoid picking.',
        medicinal_elements: 'Baby or mineral oil (drug-free scale softener); mild emollients; antifungal or low-strength anti-inflammatory creams (only if recommended by a clinician for stubborn cases).',
        when_to_see_doctor: 'See a doctor if the skin becomes very red or weepy, spreads widely, looks infected, the baby is uncomfortable, or it does not improve with simple care.',
        prevention: 'Routine gentle scalp washing helps; the condition is largely developmental and cannot be fully prevented.',
        vaccination_info: 'No vaccine is relevant to cradle cap.',
        prognosis: 'Excellent; cradle cap almost always clears by around 12 months of age.',
        recovery_timeline: 'Often improves over weeks with gentle care and resolves within the first year.',
        complications: 'Rarely, secondary infection of broken skin.',
        related_diseases: ['Atopic Dermatitis (Infantile Eczema)'],
        tags: ['cradle cap', 'seborrheic dermatitis', 'scalp', 'flaking'],
        imagePath: img('rash')
    },
    {
        id: 'head_lice', body_system: 'infect', category: 'infect_bacterial',
        name: 'Head Lice (Pediculosis Capitis)',
        classification: 'Infestation of the scalp by human head lice; a nuisance, not a disease, and not a sign of poor hygiene.',
        affected_age_group: 'Most common in school-age children, 3–11 years.',
        causes: 'Tiny wingless insects spread mainly by direct head-to-head contact and, less often, by shared combs, hats, or bedding.',
        pathophysiology: 'Lice live on the scalp feeding on blood and lay eggs (nits) glued to hair shafts; their saliva causes the itch that develops over time.',
        symptoms_early: 'Itching of the scalp, especially behind the ears and at the nape of the neck, though many children have no symptoms at first.',
        symptoms_progressive: 'Visible lice or firmly attached nits near the scalp, scratching, and sometimes small red bumps or irritation.',
        symptoms_severe: 'Scratched skin can become infected, with crusting, pus, or tender swollen neck glands.',
        urgency_level: 'mild',
        diagnosis_methods: 'Finding live lice or viable nits on close inspection, best done with a fine-toothed comb on wet conditioned hair.',
        treatment_plan: 'Apply a topical anti-louse treatment and remove nits by combing. A repeat treatment after about a week targets newly hatched lice. Treat close contacts who are affected.',
        home_care: 'Wet-comb conditioned hair every few days with a fine-toothed nit comb, wash recently used bedding and hats in hot water, and check household members. No need to treat the whole house or pets.',
        medicinal_elements: 'Permethrin (topical anti-louse active ingredient); dimeticone (physical, low-resistance topical agent that coats and immobilizes lice); wet-combing with conditioner (drug-free removal).',
        when_to_see_doctor: 'See a doctor if treatments fail, the scalp looks infected, the child is very young, or you are unsure of the diagnosis.',
        prevention: 'Avoid head-to-head contact, do not share combs or hats, and check children regularly during outbreaks; exclusion from school is generally not necessary.',
        vaccination_info: 'No vaccine is relevant to head lice.',
        prognosis: 'Excellent; lice are eliminated with correct, repeated treatment.',
        recovery_timeline: 'Live lice are usually cleared within a week or two with two correctly timed treatments plus combing.',
        complications: 'Secondary skin infection from scratching, and distress or stigma, which are unwarranted.',
        related_diseases: ['Scabies', 'Atopic Dermatitis (Infantile Eczema)'],
        tags: ['head lice', 'nits', 'scalp itch', 'parasite'],
        imagePath: img('parasite')
    },
    {
        id: 'scabies', body_system: 'derm', category: 'derm_infections',
        name: 'Scabies',
        classification: 'Intensely itchy skin infestation by the human scabies mite.',
        affected_age_group: 'All ages; in infants often involves palms, soles, and the scalp.',
        causes: 'The mite Sarcoptes scabiei, spread by prolonged skin-to-skin contact and sometimes shared bedding or clothing.',
        pathophysiology: 'Female mites burrow into the upper skin to lay eggs; an allergic reaction to the mites and their products causes the characteristic intense itch, which may take weeks to appear after a first infestation.',
        symptoms_early: 'Itching that is typically worse at night, with small red bumps.',
        symptoms_progressive: 'Thread-like burrows and a rash in the finger webs, wrists, waistline, and (in babies) palms, soles, and scalp; other close contacts often itch too.',
        symptoms_severe: 'Widespread crusted scabies (in immunocompromised children) or secondary bacterial skin infection needs prompt medical care.',
        urgency_level: 'mild',
        diagnosis_methods: 'Clinical diagnosis from the rash pattern, burrows, and itchy contacts; skin scraping under the microscope can confirm it.',
        treatment_plan: 'Apply a clinician-recommended topical scabicide to the whole body as directed, and treat all close contacts and household members at the same time, even if they have no symptoms yet.',
        home_care: 'On treatment day, wash clothing, towels, and bedding in hot water and dry on high heat, or seal non-washable items in a bag for several days. Itch can persist for weeks after successful treatment.',
        medicinal_elements: 'Permethrin cream (topical scabicide active ingredient, first-line in children); oral ivermectin (prescribed by a clinician for selected or crusted cases); emollients and clinician-advised soothing agents for residual itch.',
        when_to_see_doctor: 'See a doctor to confirm the diagnosis and for treatment, and return if itching persists beyond 2–4 weeks, the skin looks infected, or the rash worsens.',
        prevention: 'Treating all close contacts simultaneously and laundering bedding and clothing prevents reinfestation.',
        vaccination_info: 'No vaccine is relevant to scabies.',
        prognosis: 'Excellent with correct treatment of the child and contacts.',
        recovery_timeline: 'Mites are killed quickly, but the itch can take 2–4 weeks to settle as the skin recovers.',
        complications: 'Secondary bacterial infection (impetigo) and, rarely, post-streptococcal kidney inflammation.',
        related_diseases: ['Head Lice (Pediculosis Capitis)', 'Impetigo Contagiosa', 'Atopic Dermatitis (Infantile Eczema)'],
        tags: ['scabies', 'mite', 'itch', 'rash', 'parasite'],
        imagePath: img('parasite')
    },
    {
        id: 'ringworm', body_system: 'derm', category: 'derm_infections',
        name: 'Ringworm (Tinea)',
        classification: 'Common contagious fungal skin infection (not a worm).',
        affected_age_group: 'All ages; scalp ringworm is most common in school-age children.',
        causes: 'Dermatophyte fungi spread by contact with infected people, animals (especially kittens and puppies), or contaminated objects such as combs and towels.',
        pathophysiology: 'The fungus infects the dead outer layer of skin, hair, or nails, growing outward in a ring shape that gives the condition its name.',
        symptoms_early: 'A small scaly red patch that gradually enlarges.',
        symptoms_progressive: 'A ring-shaped patch with a raised, scaly border and clearer center; on the scalp, scaly patches with hair loss and sometimes broken hairs.',
        symptoms_severe: 'A boggy, tender, pus-filled scalp swelling (kerion) or widespread infection needs medical treatment to prevent scarring and hair loss.',
        urgency_level: 'mild',
        diagnosis_methods: 'Usually clinical from the appearance; skin scrapings or fungal culture confirm scalp or unclear cases.',
        treatment_plan: 'Skin ringworm responds to topical antifungal creams. Scalp and nail ringworm require clinician-prescribed oral antifungal medication because creams cannot reach the fungus.',
        home_care: 'Apply topical antifungal as directed for skin lesions, keep the area clean and dry, do not share combs, towels, or hats, and have pets checked and treated if they are the source.',
        medicinal_elements: 'Topical clotrimazole or terbinafine (antifungal active ingredients for skin ringworm); oral griseofulvin or terbinafine (prescribed by a clinician for scalp or nail involvement).',
        when_to_see_doctor: 'See a doctor for scalp involvement or hair loss, lesions that do not respond to over-the-counter creams, widespread infection, or a tender boggy scalp swelling.',
        prevention: 'Avoid sharing personal items, keep skin clean and dry, and treat infected pets and contacts.',
        vaccination_info: 'No vaccine is relevant to ringworm.',
        prognosis: 'Excellent; skin lesions clear with topical therapy and scalp infection with oral therapy.',
        recovery_timeline: 'Skin ringworm clears in 2–4 weeks of treatment; scalp ringworm needs several weeks of oral medication.',
        complications: 'Permanent hair loss or scarring from untreated scalp infection, and secondary bacterial infection.',
        related_diseases: ['Atopic Dermatitis (Infantile Eczema)', 'Pityriasis Rosea', 'Impetigo Contagiosa'],
        tags: ['ringworm', 'tinea', 'fungal infection', 'rash'],
        imagePath: img('microbe')
    },
    {
        id: 'urticaria', body_system: 'immuno', category: 'immuno_allergy',
        name: 'Urticaria (Hives)',
        classification: 'Raised, itchy welts from temporary leakage of fluid from small skin blood vessels.',
        affected_age_group: 'All ages.',
        causes: 'Often viral infections in children; also foods, medicines, insect stings, or contact triggers. Many acute cases have no identified cause.',
        pathophysiology: 'Release of histamine from skin mast cells makes small vessels leaky, producing the itchy raised wheals that move around and fade within hours.',
        symptoms_early: 'Sudden itchy raised welts, pink with paler centers, that come and go.',
        symptoms_progressive: 'Welts of varying size that move location, individually lasting less than 24 hours; sometimes soft swelling of the lips or eyelids (angioedema).',
        symptoms_severe: 'Swelling of the tongue or throat, trouble breathing, drooling, vomiting, dizziness, or collapse signal anaphylaxis — a medical emergency.',
        urgency_level: 'moderate',
        diagnosis_methods: 'Clinical diagnosis from the typical fleeting welts; testing is reserved for clear trigger patterns or chronic cases.',
        treatment_plan: 'Remove any obvious trigger and treat itch with a non-sedating antihistamine. Anaphylaxis is treated immediately with intramuscular epinephrine.',
        home_care: 'Avoid known triggers, keep the child cool, and use cool compresses for itch. Watch closely for any breathing or swallowing difficulty.',
        medicinal_elements: 'Cetirizine or loratadine (non-sedating antihistamine active ingredients for itch); epinephrine (intramuscular active ingredient for anaphylaxis, given immediately); cool compresses (drug-free relief).',
        when_to_see_doctor: 'Call emergency services for any trouble breathing, throat or tongue swelling, repeated vomiting, or faintness. See a doctor for hives lasting more than 6 weeks, hives with joint swelling, or an unclear trigger.',
        prevention: 'Avoiding identified triggers prevents recurrences; many acute cases cannot be prevented.',
        vaccination_info: 'No vaccine prevents hives; children with a history of anaphylaxis should discuss vaccination safely with their clinician.',
        prognosis: 'Good; most acute hives resolve within days, though chronic hives can persist for months and usually settle over time.',
        recovery_timeline: 'Acute urticaria typically fades within hours to a few days; chronic urticaria is defined as lasting more than 6 weeks.',
        complications: 'Progression to anaphylaxis when part of a severe allergic reaction; sleep disruption from itch.',
        related_diseases: ['Anaphylaxis (Pediatric)', "Cow's Milk Protein Allergy (CMPA)", 'Atopic Dermatitis (Infantile Eczema)', 'Allergic Rhinitis (Hay Fever)'],
        tags: ['hives', 'urticaria', 'allergy', 'itch', 'welts'],
        imagePath: img('rash')
    },
    {
        id: 'oral_thrush', body_system: 'infect', category: 'infect_bacterial',
        name: 'Oral Thrush (Oral Candidiasis)',
        classification: 'Common yeast infection of the mouth in infants.',
        affected_age_group: 'Mostly young infants; also children using inhaled steroids or after antibiotics.',
        causes: 'Overgrowth of Candida yeast, favored by the immature infant immune system, antibiotics, or inhaled corticosteroids.',
        pathophysiology: 'Candida overgrows on the moist lining of the mouth, forming adherent white plaques; it is usually a nuisance rather than a serious infection in healthy infants.',
        symptoms_early: 'White patches on the tongue, gums, or inner cheeks that, unlike milk, do not wipe away easily.',
        symptoms_progressive: 'More extensive white plaques, mild fussiness or reduced feeding, and sometimes a linked diaper yeast rash.',
        symptoms_severe: 'Refusal to feed, dehydration, thrush in an unwell or immunocompromised child, or spread beyond the mouth needs prompt medical assessment.',
        urgency_level: 'mild',
        diagnosis_methods: 'Clinical diagnosis from the typical non-wipeable white plaques; swabs are rarely needed.',
        treatment_plan: 'A clinician-prescribed topical antifungal applied to the mouth clears most cases. Treating a breastfeeding mother’s nipples at the same time prevents back-and-forth reinfection.',
        home_care: 'Sterilize bottle nipples, pacifiers, and breast-pump parts; offer feeds patiently. Continue prescribed antifungal for the full course even after plaques clear.',
        medicinal_elements: 'Nystatin oral suspension (topical antifungal active ingredient); miconazole oral gel (alternative topical antifungal for older infants, used as directed); sterilization of feeding equipment (drug-free measure).',
        when_to_see_doctor: 'See a doctor if feeding is poor, the baby is dehydrated, thrush keeps returning, the child is otherwise unwell, or it does not clear with treatment.',
        prevention: 'Sterilizing feeding equipment, rinsing the mouth after inhaled steroids, and treating maternal nipple thrush reduce recurrence.',
        vaccination_info: 'No vaccine is relevant to oral thrush.',
        prognosis: 'Excellent in healthy infants; clears readily with treatment.',
        recovery_timeline: 'Usually improves within a few days and clears within 1–2 weeks of antifungal treatment.',
        complications: 'Feeding difficulty, linked diaper rash, and recurrence; serious spread mainly in immunocompromised children.',
        related_diseases: ['Diaper Dermatitis (Diaper Rash)'],
        tags: ['thrush', 'oral candidiasis', 'white patches', 'infant feeding'],
        imagePath: img('microbe')
    },
    {
        id: 'enuresis', body_system: 'renal', category: 'renal_urological',
        name: 'Nocturnal Enuresis (Bedwetting)',
        classification: 'Involuntary night-time wetting beyond the age when bladder control is expected.',
        affected_age_group: 'Children 5 years and older; common and usually outgrown.',
        causes: 'A combination of deep sleep with reduced arousal to a full bladder, a smaller night-time bladder capacity, and higher overnight urine production; often runs in families. Most children have no underlying disease.',
        pathophysiology: 'The brain does not wake the child when the bladder is full at night, so the bladder empties during sleep; maturation of this signaling resolves most cases over time.',
        symptoms_early: 'Wetting during sleep in a child over 5 who is dry by day.',
        symptoms_progressive: 'Continued night-time wetting that can affect a child’s confidence and willingness to attend sleepovers.',
        symptoms_severe: 'Daytime wetting, painful urination, excessive thirst, snoring with pauses, new bedwetting after being dry for months, or constipation point to a treatable cause that needs evaluation.',
        urgency_level: 'mild',
        diagnosis_methods: 'History and examination with a urine test to exclude infection or diabetes; most cases need no further testing.',
        treatment_plan: 'Reassurance and simple measures first; a bedwetting alarm is the most effective long-term treatment. Medication may be used short-term, for example for sleepovers, under clinician guidance.',
        home_care: 'Encourage daytime fluids but limit drinks close to bedtime, ensure a toilet visit before sleep, treat any constipation, and use praise and reward charts rather than punishment.',
        medicinal_elements: 'Bedwetting alarm (drug-free conditioning device, most effective long term); desmopressin (active ingredient that reduces overnight urine, used short-term under clinician guidance); constipation treatment when relevant.',
        when_to_see_doctor: 'See a doctor for daytime wetting, painful or frequent urination, excessive thirst, snoring with breathing pauses, or new bedwetting after a long dry period.',
        prevention: 'Treating constipation and establishing good fluid and toileting routines help; primary bedwetting is developmental and not the child’s fault.',
        vaccination_info: 'No vaccine is relevant to bedwetting.',
        prognosis: 'Excellent; about 15% of bedwetting children become dry each year even without treatment, and alarms help most others.',
        recovery_timeline: 'Bedwetting alarms typically work over 6–12 weeks of consistent use; many children resolve spontaneously with age.',
        complications: 'Mainly emotional — embarrassment and reduced self-esteem — which respond to a supportive, blame-free approach.',
        related_diseases: ['Urinary Tract Infection (UTI)', 'Type 1 Diabetes Mellitus (Pediatric)', 'Functional Constipation'],
        tags: ['bedwetting', 'enuresis', 'night wetting', 'bladder'],
        imagePath: img('kidney_filter')
    },
    {
        id: 'type2_diabetes', body_system: 'endo', category: 'endo_pancreatic',
        name: 'Type 2 Diabetes Mellitus (Pediatric)',
        classification: 'Chronic disorder of high blood sugar from insulin resistance and relative insulin deficiency.',
        affected_age_group: 'Increasingly seen in older children and adolescents, often around puberty.',
        causes: 'Insulin resistance driven by excess weight, physical inactivity, family history, and certain ethnic backgrounds; puberty hormones further reduce insulin sensitivity.',
        pathophysiology: 'Body tissues respond poorly to insulin, so the pancreas makes more until it can no longer keep up, and blood sugar rises. Unlike type 1, some insulin production usually continues.',
        symptoms_early: 'Often few or no symptoms; gradual increased thirst and urination, tiredness, and a dark velvety neck skin (acanthosis nigricans).',
        symptoms_progressive: 'Increased thirst and urination, blurred vision, slow-healing infections, and fatigue as blood sugars climb.',
        symptoms_severe: 'Marked dehydration, vomiting, rapid breathing, abdominal pain, or confusion can signal dangerously high blood sugar and require emergency care.',
        urgency_level: 'severe',
        diagnosis_methods: 'Blood tests for fasting or random glucose and HbA1c; antibody and insulin tests help distinguish type 2 from type 1 diabetes.',
        treatment_plan: 'Lifestyle change is the foundation, combined with clinician-prescribed medication (often metformin) and sometimes insulin. Care is led by a pediatric diabetes team.',
        home_care: 'Support balanced family meals, daily physical activity, healthy weight, blood sugar monitoring as advised, and regular review of eyes, kidneys, and feet.',
        medicinal_elements: 'Metformin (oral active ingredient that improves insulin sensitivity, first-line in children); insulin (active hormone used when needed); structured lifestyle and nutrition therapy (drug-free cornerstone).',
        when_to_see_doctor: 'Seek urgent care for vomiting, rapid breathing, drowsiness, or severe dehydration. See a doctor for excessive thirst and urination, unexplained tiredness, or risk factors such as obesity and family history.',
        prevention: 'A healthy diet, regular activity, and maintaining a healthy weight substantially reduce risk; screening is advised for higher-risk children.',
        vaccination_info: 'No vaccine prevents type 2 diabetes; children with diabetes should stay current on routine and influenza vaccines.',
        prognosis: 'Good blood sugar control prevents complications; the condition is chronic and needs lifelong management.',
        recovery_timeline: 'Blood sugars can improve within weeks to months of lifestyle change and medication; management is ongoing.',
        complications: 'Long-term damage to eyes, kidneys, nerves, and blood vessels, and acute very high blood sugar states.',
        related_diseases: ['Type 1 Diabetes Mellitus (Pediatric)', 'Childhood Obesity'],
        tags: ['type 2 diabetes', 'blood sugar', 'insulin resistance', 'obesity'],
        imagePath: img('diabetes')
    },
    {
        id: 'obesity', body_system: 'nutri', category: 'nutri_macro',
        name: 'Childhood Obesity',
        classification: 'Excess body fat that increases the risk of health problems, defined by age- and sex-specific BMI charts.',
        affected_age_group: 'All ages; a major and growing pediatric health concern.',
        causes: 'A long-term imbalance between calories taken in and used, shaped by diet, physical activity, sleep, genetics, environment, and rarely an underlying medical or hormonal condition.',
        pathophysiology: 'Surplus energy is stored as fat; excess fat tissue alters hormones and metabolism, raising the risk of insulin resistance, high blood pressure, and fatty liver over time.',
        symptoms_early: 'Weight and BMI tracking above the healthy range for age on growth charts, often without other symptoms.',
        symptoms_progressive: 'Breathlessness on exertion, joint or leg discomfort, snoring or disrupted sleep, dark velvety neck skin, and emotional or social difficulties.',
        symptoms_severe: 'Severe breathing problems during sleep, signs of type 2 diabetes, very high blood pressure, or significant emotional distress need prompt medical attention.',
        urgency_level: 'moderate',
        diagnosis_methods: 'BMI plotted on age- and sex-specific charts, growth review, and assessment for complications and, when indicated, underlying causes.',
        treatment_plan: 'Family-based lifestyle change is the core treatment, supported by a healthcare team, focused on sustainable eating, activity, sleep, and emotional wellbeing rather than rapid weight loss.',
        home_care: 'Offer regular balanced family meals with vegetables and fewer sugary drinks and snacks, aim for about an hour of daily activity, limit screen time, prioritize sleep, and keep messaging positive and shame-free.',
        medicinal_elements: 'Structured lifestyle and nutrition therapy (drug-free cornerstone); treatment of complications such as type 2 diabetes when present; medication or specialist care reserved for selected cases under expert guidance.',
        when_to_see_doctor: 'See a doctor to review growth and screen for complications, and sooner for breathing problems during sleep, excessive thirst and urination, severe joint pain, or emotional distress.',
        prevention: 'Breastfeeding in infancy, family meals, limiting sugary drinks, daily activity, adequate sleep, and reduced screen time help prevent obesity.',
        vaccination_info: 'No vaccine is relevant to obesity.',
        prognosis: 'Sustained family lifestyle changes improve weight trajectory and reduce future disease risk; established obesity tends to persist into adulthood without support.',
        recovery_timeline: 'Healthy changes show benefits over months; the goal in growing children is often to slow weight gain while height increases.',
        complications: 'Type 2 diabetes, high blood pressure, fatty liver, sleep apnea, joint problems, and low self-esteem.',
        related_diseases: ['Type 2 Diabetes Mellitus (Pediatric)', 'Pediatric Generalized Anxiety Disorder (GAD)'],
        tags: ['obesity', 'overweight', 'weight', 'lifestyle', 'nutrition'],
        imagePath: img('growth')
    },
    {
        id: 'pda', body_system: 'cardio', category: 'cardio_congenital',
        name: 'Patent Ductus Arteriosus (PDA)',
        classification: 'Congenital heart condition in which a normal fetal blood vessel fails to close after birth.',
        affected_age_group: 'Newborns and infants; more common in premature babies.',
        causes: 'The ductus arteriosus, which bypasses the lungs before birth, normally closes in the first days of life; in PDA it stays open, more often in premature infants and after congenital rubella.',
        pathophysiology: 'The open vessel lets blood flow from the aorta back into the lung circulation, increasing blood flow to the lungs and workload on the heart; large shunts strain the heart over time.',
        symptoms_early: 'Often none with a small PDA; a heart murmur may be the only finding.',
        symptoms_progressive: 'With a larger PDA: fast breathing, sweating or tiring during feeds, poor weight gain, and frequent chest infections.',
        symptoms_severe: 'Signs of heart failure — marked breathlessness, poor feeding, and failure to thrive — need prompt cardiology care.',
        urgency_level: 'moderate',
        diagnosis_methods: 'Detection of a characteristic murmur followed by echocardiography, which confirms the diagnosis and measures the size of the shunt.',
        treatment_plan: 'Small PDAs may close on their own or simply be monitored. In premature infants, medication may help closure; significant PDAs are closed with a catheter procedure or surgery.',
        home_care: 'Attend cardiology follow-up, support feeding and growth, watch for breathing or feeding difficulty, and keep up with routine vaccines and good dental care.',
        medicinal_elements: 'Ibuprofen or indomethacin (active ingredients used in premature infants to promote ductal closure, under specialist care); catheter device closure or surgical ligation (definitive procedures).',
        when_to_see_doctor: 'See a doctor for fast breathing, sweating or tiring with feeds, poor weight gain, or any concern raised at newborn checks; attend all cardiology appointments.',
        prevention: 'Rubella vaccination of future mothers prevents PDA caused by congenital rubella; most PDA is not preventable.',
        vaccination_info: 'Routine immunizations are important; some children with heart conditions also receive RSV protection in infancy.',
        prognosis: 'Excellent after closure; small PDAs often need only monitoring.',
        recovery_timeline: 'Recovery from catheter closure is usually quick, within days; surgical recovery takes a few weeks.',
        complications: 'Heart failure, recurrent chest infections, poor growth, and a small long-term risk of heart-valve infection (endocarditis).',
        related_diseases: ['Ventricular Septal Defect (VSD)', 'Atrial Septal Defect (ASD)', 'Prematurity & Low Birth Weight'],
        tags: ['pda', 'congenital heart defect', 'murmur', 'newborn heart'],
        imagePath: img('heart_defect')
    },
    {
        id: 'asd', body_system: 'cardio', category: 'cardio_congenital',
        name: 'Atrial Septal Defect (ASD)',
        classification: 'Congenital opening in the wall between the heart’s two upper chambers.',
        affected_age_group: 'Present from birth; often detected in childhood or sometimes later.',
        causes: 'A hole in the atrial septum that fails to close during heart development; usually occurs by chance, sometimes with genetic syndromes or family history.',
        pathophysiology: 'Blood flows through the opening from the left to the right atrium, sending extra blood to the lungs and the right side of the heart, which can enlarge over years if the defect is large.',
        symptoms_early: 'Often no symptoms in childhood; a heart murmur may be the only sign.',
        symptoms_progressive: 'A larger defect can cause tiring easily, breathlessness on exertion, frequent chest infections, or poor weight gain.',
        symptoms_severe: 'Significant breathlessness, heart rhythm problems, or signs of heart strain warrant prompt cardiology review.',
        urgency_level: 'moderate',
        diagnosis_methods: 'A murmur prompting echocardiography, which confirms the defect, its size, and its effect on the heart chambers.',
        treatment_plan: 'Small ASDs often close on their own and are monitored. Defects that remain significant are closed with a catheter device or surgery, usually in early childhood.',
        home_care: 'Attend cardiology follow-up, support normal activity and growth, and keep up with routine vaccines and good dental hygiene.',
        medicinal_elements: 'Catheter device closure (minimally invasive procedure for suitable defects); surgical repair (for larger or unsuitable defects); routine follow-up imaging (monitoring, not medication).',
        when_to_see_doctor: 'See a doctor for breathlessness, tiring easily, poor growth, frequent chest infections, or any murmur noted at a check-up.',
        prevention: 'Most ASDs cannot be prevented; good prenatal care and avoiding alcohol and harmful exposures in pregnancy support healthy heart development.',
        vaccination_info: 'Keep routine immunizations up to date; discuss any additional protections with the cardiology team.',
        prognosis: 'Excellent after timely closure; outcomes are very good when treated in childhood.',
        recovery_timeline: 'Catheter closure recovery takes days; surgical repair recovery takes several weeks.',
        complications: 'If left untreated into adulthood: heart rhythm problems, right-heart enlargement, and raised lung blood pressure.',
        related_diseases: ['Ventricular Septal Defect (VSD)', 'Patent Ductus Arteriosus (PDA)', 'Down Syndrome (Trisomy 21)'],
        tags: ['asd', 'congenital heart defect', 'hole in heart', 'murmur'],
        imagePath: img('heart_defect')
    },
    {
        id: 'myocarditis', body_system: 'cardio', category: 'cardio_inflammatory',
        name: 'Pediatric Myocarditis',
        classification: 'Inflammation of the heart muscle, most often following a viral infection.',
        affected_age_group: 'All ages, including infants and adolescents.',
        causes: 'Usually viral infections; less often other infections, immune reactions, or medications. The immune response to infection inflames the heart muscle.',
        pathophysiology: 'Inflammation weakens the heart muscle so it pumps less effectively, which can cause heart failure and dangerous rhythm disturbances in severe cases.',
        symptoms_early: 'A recent viral illness followed by tiredness, poor feeding in infants, and a faster heartbeat.',
        symptoms_progressive: 'Breathlessness, chest pain, fast or irregular heartbeat, reduced exercise tolerance, and swelling of the feet or abdomen.',
        symptoms_severe: 'Severe breathlessness, fainting, gray or mottled color, cold hands and feet, or collapse indicate a life-threatening emergency.',
        urgency_level: 'emergency',
        diagnosis_methods: 'ECG, blood markers of heart injury, echocardiography, and sometimes cardiac MRI; care is led by a pediatric cardiology team.',
        treatment_plan: 'Hospital care to support heart function, treat heart failure and rhythm problems, and rest the heart; severe cases may need intensive care and advanced support.',
        home_care: 'There is no home treatment for acute myocarditis. After recovery, follow the cardiology team’s guidance on a gradual return to activity and avoid strenuous exercise until cleared.',
        medicinal_elements: 'Diuretic active ingredients and heart-support medications (used in hospital to treat heart failure); rhythm-control therapies (as needed); supervised activity restriction (a key non-drug measure during recovery).',
        when_to_see_doctor: 'Call emergency services for breathlessness, chest pain, fainting, a very fast or irregular heartbeat, or a gray, mottled, or unwell child after a viral illness.',
        prevention: 'Routine childhood vaccines prevent some infections that can cause myocarditis; good hand hygiene reduces viral spread.',
        vaccination_info: 'Vaccination against influenza and other infections reduces some causes; discuss any concerns with your clinician.',
        prognosis: 'Variable — many children recover well, but some develop lasting heart muscle weakness; early specialist care improves outcomes.',
        recovery_timeline: 'Recovery ranges from weeks to several months, with cardiology follow-up to monitor heart function.',
        complications: 'Heart failure, dangerous rhythm disturbances, and chronic weakening of the heart muscle (dilated cardiomyopathy).',
        related_diseases: ['Kawasaki Disease', 'Acute Rheumatic Fever (ARF)', 'Pediatric Influenza (Flu)'],
        tags: ['myocarditis', 'heart inflammation', 'heart failure', 'emergency'],
        imagePath: img('heart_inflammation')
    },
    {
        id: 'hus', body_system: 'renal', category: 'renal_glomerular',
        name: 'Hemolytic Uremic Syndrome (HUS)',
        classification: 'Serious condition combining red-cell destruction, low platelets, and acute kidney injury.',
        affected_age_group: 'Most common in children under 5 years.',
        causes: 'Usually follows infection with Shiga-toxin-producing E. coli (often from undercooked meat or contaminated food or water) causing bloody diarrhea; less common forms have other triggers.',
        pathophysiology: 'A toxin damages the lining of small blood vessels, especially in the kidneys, where clots form, red cells are destroyed as they pass through, platelets are consumed, and kidney filtering fails.',
        symptoms_early: 'Several days of diarrhea, often bloody, with abdominal pain and vomiting.',
        symptoms_progressive: 'As diarrhea settles: paleness, tiredness, reduced urine output, irritability, and easy bruising.',
        symptoms_severe: 'Very little or no urine, swelling, seizures, severe lethargy, or breathing difficulty are emergencies requiring immediate hospital care.',
        urgency_level: 'emergency',
        diagnosis_methods: 'Blood tests showing anemia, low platelets, and impaired kidney function, with stool testing for the responsible bacteria.',
        treatment_plan: 'Hospital supportive care is the mainstay — careful fluid and electrolyte management, treatment of anemia, and dialysis for severe kidney failure. Antibiotics and anti-diarrheal medicines are generally avoided in toxin-related HUS.',
        home_care: 'There is no home treatment; the priority is recognizing warning signs early. After recovery, attend kidney follow-up because some children have lasting effects.',
        medicinal_elements: 'Intravenous fluids and electrolyte management (hospital supportive care); dialysis (kidney support for severe injury); red-cell transfusion (for significant anemia). Antibiotics are generally avoided in typical HUS.',
        when_to_see_doctor: 'Seek urgent care for bloody diarrhea, and emergency care for reduced or absent urination, marked paleness, swelling, drowsiness, or seizures after a diarrheal illness.',
        prevention: 'Thoroughly cooking meat, washing hands and produce, avoiding unpasteurized milk and juice, and safe water prevent the E. coli infections that trigger most cases.',
        vaccination_info: 'No vaccine prevents typical HUS; preventing the underlying infection is key.',
        prognosis: 'Most children recover kidney function with timely care, but a minority have lasting kidney damage and need long-term follow-up.',
        recovery_timeline: 'The acute illness lasts 1–3 weeks; kidney recovery is monitored over months.',
        complications: 'Long-term kidney damage or high blood pressure, and acute effects on the brain, heart, and pancreas.',
        related_diseases: ['Acute Gastroenteritis (Stomach Flu)', 'Shigellosis', 'Minimal Change Disease (Pediatric Nephrotic Syndrome)'],
        tags: ['hus', 'kidney injury', 'bloody diarrhea', 'e coli', 'emergency'],
        imagePath: img('kidney_filter')
    },
    {
        id: 'hsp', body_system: 'cardio', category: 'cardio_inflammatory',
        name: 'Henoch-Schönlein Purpura (IgA Vasculitis)',
        classification: 'The most common childhood vasculitis, inflaming small blood vessels in the skin, joints, gut, and kidneys.',
        affected_age_group: 'Most common between 3 and 10 years, often after a respiratory infection.',
        causes: 'An immune reaction, frequently triggered by a viral or streptococcal upper respiratory infection, that deposits IgA antibodies in small blood vessels.',
        pathophysiology: 'IgA immune complexes inflame small vessels, making them leaky and causing the characteristic rash, joint swelling, abdominal pain, and sometimes kidney inflammation.',
        symptoms_early: 'A raised purple-red rash (palpable purpura), typically on the lower legs and buttocks, that does not fade when pressed.',
        symptoms_progressive: 'Swollen, painful joints (often ankles and knees), crampy abdominal pain, and sometimes blood in the urine or stool.',
        symptoms_severe: 'Severe abdominal pain or vomiting (which can signal bowel folding/intussusception), significant blood in urine, swelling, or high blood pressure need urgent assessment.',
        urgency_level: 'moderate',
        diagnosis_methods: 'Largely clinical from the typical rash and features, supported by urine tests and blood pressure checks to detect kidney involvement; biopsy is occasionally needed.',
        treatment_plan: 'Most cases are managed supportively with rest, pain relief, and hydration. Clinician-prescribed corticosteroids may help severe joint or abdominal symptoms; kidney involvement needs specialist monitoring.',
        home_care: 'Rest, fluids, and simple pain relief for joint discomfort. Attend the scheduled urine and blood-pressure checks, as kidney involvement can appear weeks after the rash.',
        medicinal_elements: 'Acetaminophen/Paracetamol or ibuprofen (pain relief, with ibuprofen avoided if kidneys are affected); corticosteroid active ingredients (prescribed for severe abdominal or joint symptoms); scheduled urine monitoring (key non-drug surveillance).',
        when_to_see_doctor: 'See a doctor to confirm the diagnosis, and seek urgent care for severe abdominal pain or vomiting, blood in urine or stool, swelling, or testicular pain.',
        prevention: 'No specific prevention; it often follows a common infection that cannot be reliably avoided.',
        vaccination_info: 'No vaccine prevents HSP; routine immunizations should continue as advised.',
        prognosis: 'Generally excellent; most children recover fully, though kidney involvement requires follow-up because it can persist.',
        recovery_timeline: 'The acute illness usually lasts about 4–6 weeks; relapses can occur, and kidney monitoring continues for up to 6–12 months.',
        complications: 'Kidney inflammation (the main long-term concern), bowel folding (intussusception), and rarely bowel or testicular problems.',
        related_diseases: ['Immune Thrombocytopenia (ITP)', 'Intussusception', 'Acute Post-Streptococcal Glomerulonephritis (APSGN)', 'Kawasaki Disease'],
        tags: ['hsp', 'iga vasculitis', 'purpura', 'rash', 'joint pain'],
        imagePath: img('bleeding')
    },
    {
        id: 'mumps', body_system: 'infect', category: 'infect_exanthems',
        name: 'Mumps',
        classification: 'Contagious viral infection best known for swelling of the salivary glands.',
        affected_age_group: 'Children and adolescents; far less common where MMR vaccination is routine.',
        causes: 'The mumps virus, spread by respiratory droplets and saliva.',
        pathophysiology: 'The virus infects and inflames the salivary glands, especially the parotid glands in front of the ears, and can spread to other tissues such as the testes, ovaries, pancreas, or the lining of the brain.',
        symptoms_early: 'Fever, headache, muscle aches, tiredness, and loss of appetite for a day or two.',
        symptoms_progressive: 'Painful swelling of one or both cheeks and jaw (parotid glands), worse with chewing or sour foods.',
        symptoms_severe: 'Severe headache with neck stiffness, persistent vomiting, testicular pain and swelling, severe abdominal pain, or hearing changes need prompt medical care.',
        urgency_level: 'moderate',
        diagnosis_methods: 'Usually clinical from the typical gland swelling; saliva, urine, or blood tests confirm the diagnosis when needed.',
        treatment_plan: 'No specific antiviral treatment; care is supportive while the infection clears. Isolation prevents spread to others.',
        home_care: 'Rest, fluids, soft foods that need little chewing, and pain relief for fever and gland discomfort. Cold or warm packs on swollen glands may help. Keep the child away from others until no longer infectious.',
        medicinal_elements: 'Acetaminophen/Paracetamol or ibuprofen (fever and pain relief); supportive fluids and soft diet (drug-free care). There is no specific antiviral.',
        when_to_see_doctor: 'See a doctor to confirm the diagnosis, and seek urgent care for severe headache with neck stiffness, repeated vomiting, testicular pain, severe abdominal pain, or hearing problems.',
        prevention: 'The MMR vaccine is highly effective at preventing mumps; two doses are routine.',
        vaccination_info: 'Mumps is prevented by the MMR vaccine given at 12–15 months and again at 4–6 years.',
        prognosis: 'Most children recover fully within 1–2 weeks; serious complications are uncommon, especially in vaccinated children.',
        recovery_timeline: 'Gland swelling and symptoms usually resolve within about 10 days.',
        complications: 'Inflammation of the brain lining (meningitis), testes or ovaries, pancreas, and rarely permanent hearing loss.',
        related_diseases: ['Measles (Rubeola)', 'Rubella (German Measles)', 'Acute Bacterial Meningitis'],
        tags: ['mumps', 'parotitis', 'gland swelling', 'mmr', 'viral'],
        imagePath: img('throat')
    },
    {
        id: 'rubella', body_system: 'infect', category: 'infect_exanthems',
        name: 'Rubella (German Measles)',
        classification: 'Usually mild contagious viral infection that is dangerous in pregnancy.',
        affected_age_group: 'Children and adolescents; rare where MMR vaccination is routine.',
        causes: 'The rubella virus, spread by respiratory droplets; an infected pregnant woman can pass it to her unborn baby.',
        pathophysiology: 'The virus causes a mild systemic infection with a rash and swollen glands; in early pregnancy it can cross the placenta and cause serious birth defects (congenital rubella syndrome).',
        symptoms_early: 'Low-grade fever, mild cold-like symptoms, and tender swollen glands behind the ears and at the back of the neck.',
        symptoms_progressive: 'A fine pink rash that starts on the face and spreads down the body, fading after a few days; older children and adults may have joint aches.',
        symptoms_severe: 'Serious illness is uncommon in children; the main danger is infection of a pregnant woman, which threatens the unborn baby.',
        urgency_level: 'moderate',
        diagnosis_methods: 'Clinical suspicion confirmed by blood or swab tests, which is important for public health and to protect pregnant contacts.',
        treatment_plan: 'No specific treatment; supportive care while the mild illness clears, with isolation to protect others — especially pregnant women.',
        home_care: 'Rest, fluids, and fever relief as needed. Keep the child away from others, particularly pregnant women, until no longer infectious.',
        medicinal_elements: 'Acetaminophen/Paracetamol or ibuprofen (fever and discomfort); supportive fluids and rest (drug-free care). There is no specific antiviral.',
        when_to_see_doctor: 'See a doctor to confirm the diagnosis and report the case, and urgently if a pregnant woman may have been exposed or if the child becomes seriously unwell.',
        prevention: 'The MMR vaccine prevents rubella and protects future pregnancies; high community vaccination protects unborn babies.',
        vaccination_info: 'Rubella is prevented by the MMR vaccine at 12–15 months and 4–6 years; vaccinating children also protects pregnant women in the community.',
        prognosis: 'Excellent in children, who usually recover within a few days; the serious risk is to the unborn baby of an infected pregnant woman.',
        recovery_timeline: 'Symptoms typically resolve within 3–5 days.',
        complications: 'Rare in children (occasional joint or, very rarely, brain or bleeding problems); congenital rubella syndrome in babies of infected mothers is the major concern.',
        related_diseases: ['Measles (Rubeola)', 'Mumps', 'Roseola Infantum (Sixth Disease)', 'Erythema Infectiosum (Fifth Disease)'],
        tags: ['rubella', 'german measles', 'rash', 'mmr', 'pregnancy risk'],
        imagePath: img('rash')
    },
    {
        id: 'retinoblastoma', body_system: 'onco', category: 'onco_solid',
        name: 'Retinoblastoma',
        classification: 'Cancer of the developing retina; the most common eye cancer in children.',
        affected_age_group: 'Mostly children under 5 years, including infants.',
        causes: 'Mutations in the RB1 gene; some cases are inherited and affect both eyes, while others arise by chance in one eye.',
        pathophysiology: 'Loss of a tumor-suppressor gene lets immature retinal cells grow uncontrolled, forming a tumor that can threaten vision and, if untreated, spread beyond the eye.',
        symptoms_early: 'A white reflection in the pupil instead of the normal red reflex, often first noticed in flash photographs.',
        symptoms_progressive: 'A new squint (misaligned eye), a change in eye color or appearance, a red or irritated eye, or reduced vision.',
        symptoms_severe: 'A bulging or very painful eye, or signs of spread beyond the eye, indicate advanced disease requiring urgent specialist care.',
        urgency_level: 'emergency',
        diagnosis_methods: 'Urgent examination of the eye under anesthesia by a specialist, with imaging such as ultrasound or MRI; genetic testing guides care and family screening.',
        treatment_plan: 'Individualized treatment by a specialist team may include chemotherapy, focal therapies (laser or freezing), local treatments, and, for advanced disease, removal of the eye to save the child’s life.',
        home_care: 'There is no home treatment; the priority is urgent specialist referral. Families benefit from genetic counseling and screening of siblings when an inherited form is found.',
        medicinal_elements: 'Chemotherapy agents (specialist cancer treatment to shrink tumors); focal therapies such as laser or cryotherapy (eye-preserving procedures); enucleation (surgical removal of the eye for advanced disease).',
        when_to_see_doctor: 'See a doctor urgently for any white reflection in a child’s pupil, a new squint, a change in the eye’s appearance, or loss of the normal red reflex in photos.',
        prevention: 'Inherited cases cannot be prevented, but newborn red-reflex checks, family screening, and genetic counseling allow early detection that saves sight and lives.',
        vaccination_info: 'No vaccine is relevant to retinoblastoma.',
        prognosis: 'Excellent survival when caught early in countries with prompt treatment; outcomes are far worse when diagnosis is delayed.',
        recovery_timeline: 'Treatment spans months and is followed by years of monitoring for recurrence and for new tumors in inherited cases.',
        complications: 'Vision loss, loss of the eye, spread beyond the eye if untreated, and a higher lifetime risk of other cancers in inherited forms.',
        related_diseases: ['Congenital Cataracts', 'Retinopathy of Prematurity (ROP)', 'Neuroblastoma'],
        tags: ['retinoblastoma', 'eye cancer', 'white pupil', 'leukocoria', 'vision'],
        imagePath: img('onco')
    }
];

let added = 0;
const existing = new Set(db.diseases.map(d => d.id));
for (const d of NEW) {
    if (existing.has(d.id)) {
        console.log('skip (exists):', d.id);
        continue;
    }
    // overview defaults to classification for the card/summary helpers
    if (!d.overview) d.overview = d.classification;
    db.diseases.push(d);
    added++;
}

fs.writeFileSync(srcPath, JSON.stringify(db, null, 2));
console.log(`Added ${added} diseases. New total: ${db.diseases.length}`);
